version: "3.8"

services:
  mha:
    container_name: mha
    build: .
    image: mha:latest
    restart: unless-stopped
    ports:
     - "8080:8080"
    # Uncomment the following line to enable debug mode
    # command: --debug
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      # Optional: Mount local directory to container for development
      # - ./mha:/usr/src/app/mha
